### ISSUE TITLE
larastan: not found

### ISSUE THREAD

**Issue by JuanS** [jakzal/phpqa#283]
Can't run some of the commands, like larastan or phpinsights

`/entrypoint.sh: exec: line 6: larastan: not found`
`/entrypoint.sh: exec: line 6: phpinsights: not found`

Other commands like `phpstan` or `phpmd` works just fine as expected. 

```
docker run \
    --init \
    -it \
    --rm \
    -v "$(pwd)":/project \
    -w /project \
    jakzal/phpqa \
    phpinsights
```

Am I doing anything wrong? Are these commands exepcted to be triggered differently?

**Comment by JuanS** [comment]
Just found why, some tools are not ready in PHP 8

Use `jakzal/phpqa:php7.4-alpine` will fix the issue

**Comment by jakzal** [comment]
@JuanS larastan is not a command in its own right, but a phpstan plugin.

Bare in mind that we had to isolate larastan as it was breaking on other people's projects. From the next release, you'll need to use `phpstan-larastan` as a phpstan command instead of `phpstan` if you want to use it with the larastan plugin.

**Comment by JuanS** [comment]
Understood. Thanks jakzal!
