### ISSUE TITLE
/entrypoint.sh: 6: exec: composer-normalize: not found

### ISSUE THREAD

**Issue by cavo789** [jakzal/phpqa#367]
Hello

I see in your [readme.md](https://github.com/jakzal/phpqa#available-tools) that `composer normalize` is supported by PHPQA. 

When I run the command below, I can see the correct verb is `composer-normalize`:

```bash
docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:php8.1-alpine  
```

But when I run 

```bash
docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:php8.1-alpine composer-normalize
```

it didn't work.

Same for the `jakzal/phpqa:php8.1` (not the alpine) image.

But, if I try another tool like `composer-unused`, it works.

The returned error is `/entrypoint.sh: 6: exec: composer-normalize: not found`.

Thanks!

**Comment by jakzal** [comment]
Thanks for reporting. It could be caused by the fact that composer-normalize is installed as a plugin:

https://github.com/jakzal/toolbox/blob/04f63722db7d816f32c75e0269d0b2ca924b5b5d/resources/composer.json#L3-L17

while `composer-unused` is installed with phive:

https://github.com/jakzal/toolbox/blob/04f63722db7d816f32c75e0269d0b2ca924b5b5d/resources/composer.json#L18-L31

Looks like `composer-normalize` is available for phive installation, so we could change it: https://github.com/ergebnis/composer-normalize#phive

**Comment by dkarlovi** [comment]
The issue is very likely to be caused by the fact the normalize plugin is not whitelisted by the image, I just ran into this issue.

**Comment by dkarlovi** [comment]
Might be also caused by https://github.com/jakzal/phpqa/issues/369

**Comment by cavo789** [comment]
First of all, sorry for the delay in my response. I was enjoying some holidays.

Back to work and yep, thanks Dalibor, `composer normalize` is the correct action (and not `composer-normalize`).

Note: running `docker run -it --rm jakzal/phpqa` (the latest version thus) sill list `composer-normalize` (so the incorrect verb).

Many thanks!
